#!/bin/bash
# 容器环境内核参数优化演示脚本（仅展示，不修改系统）
# 安全：本脚本仅打印建议的内核参数，不执行任何修改操作

echo "=========================================="
echo "  容器环境内核参数优化建议（演示模式）"
echo "  本脚本仅展示建议值，不会修改系统配置"
echo "=========================================="

echo ""
echo "--- 当前关键内核参数 ---"
echo "IP 转发:           $(sysctl -n net.ipv4.ip_forward 2>/dev/null || echo '无法读取')"
echo "bridge 过滤:        $(sysctl -n net.bridge.bridge-nf-call-iptables 2>/dev/null || echo '无法读取')"
echo "内存 overcommit:   $(sysctl -n vm.overcommit_memory 2>/dev/null || echo '无法读取')"
echo "swap 倾向:         $(sysctl -n vm.swappiness 2>/dev/null || echo '无法读取')"
echo "最大文件描述符:    $(sysctl -n fs.file-max 2>/dev/null || echo '无法读取')"
echo "inotify 实例限制:  $(sysctl -n fs.inotify.max_user_instances 2>/dev/null || echo '无法读取')"

echo ""
echo "--- 容器环境建议参数 ---"
echo ""
echo "# 网络优化"
echo "net.ipv4.ip_forward = 1"
echo "net.bridge.bridge-nf-call-iptables = 1"
echo ""
echo "# 内存优化"
echo "vm.overcommit_memory = 1"
echo "vm.swappiness = 10"
echo "vm.max_map_count = 262144"
echo ""
echo "# 文件系统优化"
echo "fs.file-max = 1048576"
echo "fs.inotify.max_user_instances = 8192"
echo "fs.inotify.max_user_watches = 524288"
echo ""
echo "=========================================="
echo "  如需应用以上参数，请使用 root 权限执行："
echo "  sudo sysctl -w <参数名>=<值>      # 临时生效"
echo "  或编辑 /etc/sysctl.conf 添加上述行  # 永久生效"
echo "=========================================="
