apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      hostname: user-service
      containers:
      - name: user-service
        image: user-service:2025
        imagePullPolicy: IfNotPresent
        env:
        - name: EUREKA_URL
          value: http://eureka:8080/eureka
        ports:
        - containerPort: 9090
        lifecycle:
            preStop:
              exec:
                command:
                  - "curl"
                  - "-X"
                  - "POST"
                  - "http://localhost:8081/actuator/shutdown"
        resources:
          requests:
            cpu: 1
            memory: 512Mi
          limits:
            cpu: 1
            memory: 512Mi