# blue-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-blue
  labels:
    app: python
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
      version: blue
  template:
    metadata:
      labels:
        app: python
        version: blue
    spec:
      containers:
        - name: python
          image: python-server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 500m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 100Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5